export const routesSchema = {
    home: '/',
    about: '/ve-chung-toi',
    contact: '/lien-he',
    articles: '/bai-viet',
    products: '/san-pham',
    product_detail: '/san-pham/:productSlug',
    create_product: '/san-pham/them-moi',
    error: '/*',
    // Auth Routes
    register: '/dang-ky',
    login: '/dang-nhap',
    // Private Routes
    check_out: '/thanh-toan',
    cart: '/gio-hang',
    favourite: '/yeu-thich',
    account_information: '/thong-tin-tai-khoan',
    my_order: '/don-dat-hang',
    address_book: '/so-tay-dia-chi',
    // Admin Routes
    dashboard: '/dashboard',
    dashboard_product: '/quan-ly/san-pham',
    dashboard_category: '/quan-ly/danh-muc',
    dashboard_brand: '/quan-ly/thuong-hieu',
    dashboard_order: '/quan-ly/don-dat-hang',
    dashboard_order_detail: '/quan-ly/don-dat-hang/:orderId',
    dashboard_customer: '/quan-ly/khach-hang',
    dashboard_article: '/quan-ly/bai-viet',
    dashboard_report: '/dashboard/bao-cao',
    dashboard_gallery: '/dashboard/thu-vien',
    dashboard_setting: '/dashboard/cai-dat',
    dashboard_help: '/dashboard/tro-giup',
    dashboard_faq: '/dashboard/faq',
}
